module.exports = [{
  'value': 'recommendationFront-end',
  'label': '前端-热门推荐'
}, {
  'value': 'frontFrameFront-end',
  'label': '前端-前端框架'
}, {
  'value': 'forumCommunityFront-end',
  'label': '前端-论坛社区'
}, {
  'value': 'learningPlatformFront-end',
  'label': '前端-学习平台'
}, {
  'value': 'onlineProgrammingFront-end',
  'label': '前端-在线编程'
}, {
  'value': 'javaScriptFrameworkFront-end',
  'label': '前端-JavaScript框架'
}, {
  'value': 'codeHostingFront-end',
  'label': '前端-代码托管'
}, {
  'value': 'inspectionTestFront-end',
  'label': '前端-检查测试'
}, {
  'value': 'CSSFrameworkFront-end',
  'label': '前端-CSS框架'
}, {
  'value': 'techDocFront-end',
  'label': '前端-技术文档'
}, {
  'value': 'buildToolFront-end',
  'label': '前端-构建工具'
}, {
  'value': 'blogFront-end',
  'label': '前端-技术博客'
}, {
  'value': 'githubRepositoryFront-end',
  'label': '前端-Github仓库'
}, {
  'value': 'recommendationBack-end',
  'label': '后端-热门推荐'
}, {
  'value': 'frontFrameBack-end',
  'label': '后端-后端框架'
}, {
  'value': 'forumCommunityBack-end',
  'label': '后端-论坛社区'
}, {
  'value': 'learningPlatformBack-end',
  'label': '后端-学习平台'
}, {
  'value': 'onlineProgrammingBack-end',
  'label': '后端-在线编程'
}, {
  'value': 'personalFrameworkBack-end',
  'label': '后端-个人框架'
}, {
  'value': 'codeHostingBack-end',
  'label': '后端-代码托管'
}, {
  'value': 'inspectionTestBack-end',
  'label': '后端-检查测试'
}, {
  'value': 'contentManagementBack-end',
  'label': '后端-内容管理'
}, {
  'value': 'buildToolBack-end',
  'label': '后端-构建工具'
}, {
  'value': 'recommendationDesign',
  'label': '设计-热门推荐'
}, {
  'value': 'inspiration ',
  'label': '设计-灵感采集'
}, {
  'value': 'interaction',
  'label': '设计-界面交互'
}, {
  'value': 'designSpecifications',
  'label': '设计-设计规范'
}, {
  'value': 'onlineTools',
  'label': '设计-在线工具'
}, {
  'value': 'icon',
  'label': '设计-icon图标'
}, {
  'value': 'designMaterial',
  'label': '设计-设计素材'
}, {
  'value': 'galleryMaterial',
  'label': '设计-图库素材'
}, {
  'value': 'colourAssortment',
  'label': '设计-颜色搭配'
}, {
  'value': 'fontGlyph',
  'label': '设计-字体字形'
}, {
  'value': 'learningTutorial',
  'label': '设计-学习教程'
}, {
  'value': 'designTeam',
  'label': '设计-设计团队'
}, {
  'value': 'recommendationProduct',
  'label': '产品-热门推荐'
}, {
  'value': 'productInformation ',
  'label': '产品-产品资讯'
}, {
  'value': 'prototypeTool',
  'label': '产品-原型工具'
}, {
  'value': 'mindMap',
  'label': '产品-思维导图'
}, {
  'value': 'teamwork',
  'label': '产品-协同工作'
}, {
  'value': 'documentEditing',
  'label': '产品-文档编辑'
}, {
  'value': 'diskStorage',
  'label': '产品-云盘储存'
}, {
  'value': 'interestingProducts',
  'label': '产品-趣味产品'
}, {
  'value': 'domainName',
  'label': '运营-域名注册'
}, {
  'value': 'dataAnalysis ',
  'label': '运营-数据分析'
}, {
  'value': 'dataTools',
  'label': '运营-数据工具'
}, {
  'value': 'dataCollection',
  'label': '运营-数据收集'
}, {
  'value': 'mediaPlatform',
  'label': '运营-新媒平台'
}, {
  'value': 'mediaTools',
  'label': '运营-新媒工具'
}, {
  'value': 'websiteInclusion',
  'label': '运营-网站收录'
}, {
  'value': 'ASOOptimization',
  'label': '运营-ASO优化'
}, {
  'value': 'recruitmentPlatform',
  'label': '工作-招聘平台'
}, {
  'value': 'partTimeProgram',
  'label': '工作-程序兼职'
}, {
  'value': 'partTimeDesign',
  'label': '工作-设计兼职'
}, {
  'value': 'developmentHardware',
  'label': '极客-开发硬件'
}, {
  'value': 'hardwareSystem',
  'label': '极客-硬件系统'
}, {
  'value': 'otherTools',
  'label': '极客-其他工具'
}, {
  'value': 'informationInquiry',
  'label': '极客-信息查询'
}, {
  'value': 'gameSystem',
  'label': '极客-游戏系统'
}, {
  'value': 'webGovernment',
  'label': '生活-政府网站'
}, {
  'value': 'freeVideo',
  'label': '生活-免费影视'
}]
